services:
  card.api:
    container_name: lde.card.api
    build:
      context: .
      dockerfile: Card/Card.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5006
      - ConnectionString=server=postgres;port=5432;database=cards;uid=postgres;password=postgres;
    depends_on:
      - postgres
    ports:
      - 5006:5006    
  history.api:
    container_name: lde.history.api
    build:
      context: .
      dockerfile: History/History.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5004
      - ConnectionString=server=postgres;port=5432;database=history;uid=postgres;password=postgres;
    depends_on:
      - postgres
    ports:
      - 5004:5004
  list.api:
    container_name: lde.list.api
    build:
      context: .
      dockerfile: List/List.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5009
      - ConnectionString=server=postgres;port=5432;database=lists;uid=postgres;password=postgres;
    depends_on:
      - postgres
    ports:
      - 5009:5009
  board.api:
    container_name: lde.board.api
    build:
      context: .
      dockerfile: Board/Board.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5010
      - ConnectionString=server=postgres;port=5432;database=lists;uid=postgres;password=postgres;
    depends_on:
      - postgres
    ports:
      - 5010:5010
  listcard.api:
    container_name: lde.listcard.api
    build:
      context: .
      dockerfile: ListCard/ListCard/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - CardUrl=http://card.api:5006
      - ListUrl= http://list.api:5009
    depends_on:
      - card.api
      - list.api
    ports:
      - 5002:5002
  user.api:
    container_name: lde.user.api
    build:
      context: .
      dockerfile: User/User.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5003
       - ConnectionString=server=postgres;port=5432;database=catalog;uid=postgres;password=postgres;
    depends_on:
      - postgres
    ports:
      - 5003:5003
  web.server:
    container_name: lde.web.server
    build:
      context: .
      dockerfile: Web/Web.Server/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5007
       - UserUrl=http://user.api:5003
       - ListCardUrl=http://listcard.api:5002
       - HistoryUrl=http://history.api:5004
       - BoardUrl=http://board.api:5010
    depends_on:
      - user.api
      - history.api
      - listcard.api
    ports:
      - 5007:5007
  web.client:
    container_name: web.client
    build:
     context: .
     dockerfile: Web/web.client/Dockerfile
    ports:
     - 4200:80
    depends_on:
    - web.server
  nginx:
    image: nginx
    container_name: lde.nginx
    ports:
      - 80:80
    volumes:
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./Proxy/assets:/var/www/assets
  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80 
  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4